### ISSUE TITLE
Enchant names

### ISSUE THREAD

**Issue by bartonsweb** [Zedly/Zenchantments#1]
It's possible to give the enchantments colored names via "Â§c" (This would give a red name) for the enchant. I'm sure you can add using normal color codes (With the & sign, or another traditional method). But regardless, you can currently color enchantments with the above code however it will make it impossible to register that enchantment through the /ench command. It shows as correctly colored in the /ench list. It also shows as colored on items, but it doesn't let you /ench [enchname] because it says it does not exist. Similarly you can't /ench give with it either. This is only small but allows for more customization :)

**Comment by Zedly** [comment]
Thank you for this bug report. I fixed the issue for the next update. Your feedback is greatly appreciated!

**Comment by bartonsweb** [comment]
Thank you! I have another bug to report; although you fixed the servers crashing if somebody shoots arrows into a nether portal, shooting once from a bow with spread or burst on it into a portal will lag the entire chunk to an unplayable state until the server is restarted (seems as though the portal fires endlessly back at you, though I can't be sure). Also, there are no log errors to report with this as the server doesn't have any warnings or errors from it (spigot 1.8.8) but just lags a lot.

Thanks for the awesome plugin! 
One last question; do you do any paid work I.e. Custom enchantments for specific servers etc?

David Barton

**Comment by Zedly** [comment]
Can't reproduce anymore (Maybe because this is exactly a year old today). Do you still get the problem?
