### ISSUE TITLE
grab and Shred

### ISSUE THREAD

**Issue by rock211212** [Zedly/Zenchantments#15]
if the apickaxe heve grab then Shred well not work.

**Comment by Zedly** [comment]
Hello,
Grab and Shred work fine together in the latest build. Compile the latest commit - I merged the latest updates into the main branch, it was about time.

**Comment by Xardas88** [comment]
I've the same problem. If i have OP this enchant work but not to normal player. I try to give zenchantments.* to player and doesn't work anyway
I use last release and try dev too (compiled by myself)
spigot 1.12.2

**Comment by Zedly** [comment]
Fixed.
