### ISSUE TITLE
Blaze's Curse Malfunction

### ISSUE THREAD

**Issue by MalinMiracle** [Zedly/Zenchantments#19]
Blaze's Curse seems to be damaging my players when they are standing under netherrack in the nether, as if they were standing in the rain. If they stand under any other type of material in the nether they are unaffected. The fire resistance still functions properly and they can swim through lava, and the enchantment still seems to work as advertised in the overworld.  It does not matter if it's placed netherrack or if its generated netherrack, both still cause the effect. My Minecraft version is 1.12.2.

**Comment by Zedly** [comment]
I have not been able to recreate the issue. I tried standing right below netherrack and it did not damage my player. Thoughts?
