### ISSUE TITLE
Allow console to use commands

### ISSUE THREAD

**Issue by jellz** [Zedly/Zenchantments#35]
Hi, my server's setup would greatly benefit if Zenchantments commands were able to be used by the console. Any chance you could allow commands like ench give to be used by the console?

I tried changing the code myself but I ran into a bunch of errors and I was wondering instead of having to fix them if the maintainer could just add the feature ;-)

Cheers

**Comment by CyonDev** [comment]
This would be really useful - Looking at setting up a crate to give users this enchantment. What errors were you getting ?

**Comment by jellz** [comment]
Oh, I don't have those files anymore nor do I work on that server -- I don't remember if we were able to get the code working, sorry!

**Comment by Zedly** [comment]
/ench give works from the console. Which commands are you trying to use?

**Comment by Zedly** [comment]
Oh you're the guy who sent me an email as well.. Turns out I never hit send, I'm sorry about that. I made it possible at your request.
