### ISSUE TITLE
1.15.2: Fire allows extraction of worldguard protected regions

### ISSUE THREAD

**Issue by Geolykt** [Zedly/Zenchantments#37]
World protection plugins have, per convention an event handler priority of HIGHEST, while the Zenchantment event handler has only a priority of NORMAL. This makes it so the plugin is unaware that the event has been cancelled.

To prevent this, two fixes can be applied:

1. Use the MONITOR event priority
2. Call the event again and check whether it was cancelled (may create lag, and worst case scenario - a crash)

**Comment by Geolykt** [comment]
Closed as Zenchantments doesn't support 1.15

**Comment by Zedly** [comment]
Hi, please checkout the dev2 branch which is built for 1.15.2. It uses 1.15 NMS code and is likely to work correctly with protection and logging plugins. Thanks for reporting!

**Comment by Geolykt** [comment]
The issue actually still persists in the dev2 branch.

**Comment by Geolykt** [comment]
This issue also applies to almost every enchantment, known enchantments to be affected by this are Fire and Gold rush. Reopened as it is version independent (i.e. it should occour in every version of (craft-) bukkit)

**Comment by rfrowe** [comment]
@Geolykt Are there downsides to using the MONITOR event priority?

**Comment by Geolykt** [comment]
Yes, per conventions you should not cancel the event if you are using the MONITOR event priority. Optionally, you should not really change the event as these changes may not be seen by a logging or world protection plugin. Latter is the biggest downside for the plugin, but since the plugin doesn't change the event itself, but rather changes other stuff that can hardly be detected by conventional ways. 

So the only downside is that it can interfere with other plugins, which cannot be seen in a clean install without any other plugins

**Comment by Zedly** [comment]
Fire now respects protections
