### ISSUE TITLE
1.15.2, combining books adding unbreaking 1 to every book

### ISSUE THREAD

**Issue by chrismwiggs** [Zedly/Zenchantments#40]
When combing books in an anvil on 1.15, the books show an enchantment of unbreaking.0, which when combined, creates unbreaking 1. This happens with every book (it's as if every book has unbreaking.0, which I guess makes sense if the book has no unbreaking), meaning all combined books have unbreaking 1 added to them.

![image](https://user-images.githubusercontent.com/6501625/86063460-efa93480-ba38-11ea-9499-2daf367bc4b3.png)
![image](https://user-images.githubusercontent.com/6501625/86063465-f33cbb80-ba38-11ea-80be-4e832cc79400.png)

**Comment by Zedly** [comment]
Hi, this enchantment is supposed to be temporary and I've never been able to reproduce the proble, although multiple people have reported it. Do you have a server where you can demonstrate the bug? Thanks!

**Comment by Zedly** [comment]
Accidental adding of Unbreaking I has been mitigated
