### ISSUE TITLE
BUG: Other vanilla enchantments gets hidden when custom enchantments are also applied

### ISSUE THREAD

**Issue by iCaitlyn** [Zedly/Zenchantments#43]
Server: Paper 1.15.2 (build 378) 

Plugin version: 1.15_build 4

Description:

Basically, we have recently had an issue occurring, where in the vanilla enchantments gets hidden with hideflag by the plugin. 

A user had enchanted two pickaxes, the first one only had two vanilla enchants, but neither showed up. 

The second one had two vanilla enchants, and the custom Fire enchantment.  Only the Fire enchantment showed up.

This issue hadn't occurred a month or so ago, the only changes was that the Paper's build version increased.

**Comment by Zedly** [comment]
Hi, that's a problem I haven't heard of before. Do you have a server where I can take a look at it? You can email the address to zedlydev@gmail.com! Thanks!

**Comment by iCaitlyn** [comment]
This seems to have become a non-issue for 1.15 after further updates of Paper 1.15, we have had not have any further complaints from players in the last few weeks.

Closing this issue now, as we're now looking to upgrade to 1.16.
