### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by toomanybugs1** [Zedly/Zenchantments#44]
Hello! We've been using zenchantments for a while and just got a 1.16.1 server with papermc. I the release does load but it acts strangely so I want to try to see if I can get a custom build working for us. I have been able to edit the parent pom file but I can't find the PlayerInteractUtil mentioned in the readme. Where can I find this? Thanks!

**Comment by Geolykt** [comment]
The PlayerInteractUtil class does not exist anymore. The only thing you should do it maybe remove outdated NMS and update the dependencies. Everything should be straightforward if you are already building plugins via maven

**Comment by toomanybugs1** [comment]
Okay, there's probably something I'm doing wrong on my side then. Just wanted to rule that out as a possibility. Thank you!
