### ISSUE TITLE
Spikes and Sonic shock item disappearance and Console Spam

### ISSUE THREAD

**Issue by Geolykt** [Zedly/Zenchantments#49]
The Console spam is a side effect of the item disappearance and is thrown when there is no item in hand (Null Pointer Exception).

The item disappearance is a side effect of the CompatibillityAdaper#attackEntity function, as it attempts to break the item in hand and if it has no health left (which is always the case for non-equipment items) it removes the item.

The fix could be done rather easily with overloading and a extra parameter configuring whether (or where) the item breaks.

Tested versions: none

Affected lines: 
https://github.com/Zedly/Zenchantments/blob/dev2/src/main/java/zedly/zenchantments/compatibility/CompatibilityAdapter.java#L1193
https://github.com/Zedly/Zenchantments/blob/dev2/src/main/java/zedly/zenchantments/enchantments/SonicShock.java#L37
https://github.com/Zedly/Zenchantments/blob/dev2/src/main/java/zedly/zenchantments/enchantments/Spikes.java#L36

**Comment by Zedly** [comment]
attackEntity now uses the correct item slot
