### ISSUE TITLE
Combining books with tools/armor

### ISSUE THREAD

**Issue by SignatureDom** [Zedly/Zenchantments#54]
Hello, i am physically unable to combine books with any tool or armor, it just wont let me take the tool out the finished slot 
![image](https://user-images.githubusercontent.com/71554049/123129477-4d772d80-d48f-11eb-8b61-b7566c883cb7.png)

**Comment by Geolykt** [comment]
Does using paper resolve this issue?

**Comment by Zedly** [comment]
I changed the Anvil code quite a bit, and now I can't reproduce this issue. Consider trying it again!
