### ISSUE TITLE
Enchantments not being able to be merged

### ISSUE THREAD

**Issue by Arquimecs** [Zedly/Zenchantments#58]
Hello, so i was enchanting some netherite pants with saturation III, and they already had glide 2, and it isnt applying the enchant with both, or neither is it letting me to take out the pants of the anvil

**Comment by Geolykt** [comment]
Are you using Spigot or Paper?

**Comment by Zedly** [comment]
Hi, I recently fixed a similar bug. Have you updated to build 10? If you still have the issue, join the test server linked at the download page and see if you can make it happen there!

-brain

**Comment by Zedly** [comment]
I just received a similar report, turned out they were using the wrong plugin version. Make sure the version of Zen matches your server version. Don't be afraid to install the beta if you're on 1.19, there are no known issues with it.
-brain
