### ISSUE TITLE
Rainbow Slam issue

### ISSUE THREAD

**Issue by legendcuzican13** [Zedly/Zenchantments#59]
Zenchantments throwing an error, not sure what the cause is.

![Screenshot 2023-03-18 4 00 56 PM](https://user-images.githubusercontent.com/108838775/226139911-b30f0406-4b4f-44ae-b966-3d0f58cc02b7.png)

**Comment by legendcuzican13** [comment]
Using 1.8(FlamePaper). Build found from bukkit

**Comment by Geolykt** [comment]
This is caused by your server implementation adding excessive limitations (probably to prevent hacking - but this doesn't properly guard against such usecases).
This issue can be ignored should it not have an impact in gameplay.

---
Also: 1.8.X is not supported by Zenchantments anymore

**Comment by legendcuzican13** [comment]
Ah. Thanks for the reply.

**Comment by legendcuzican13** [comment]
This was solved by as previously mentioned, changing my server implementation. (Was previously flamepaper, changed to pandaspigot)
